### ISSUE TITLE
Missing `_get_mlir` Python method binding in PyTorch Frontend

### ISSUE THREAD

**Issue by ajarthurs** [llvm/mlir-npcomp#39]
Importing the PyTorch frontend complains of a missing `_get_mlir` method in the `_torch_mlir.so` binary. I am currently on `master` (81dd571c23d489e7cc59369bda484821f6f13d3c).
```
# Build script.
LLVM_VERSION=10
export CC=clang-$LLVM_VERSION
export CXX=clang++
export LDFLAGS=-fuse-ld=$(which ld.lld)

sh ./build_tools/install_mlir.sh
sh ./build_tools/cmake_configure.sh

# Build and run tests
cd build
ninja
ninja check-npcomp
```
```
# Produce import error.
PYTHONPATH=build/python:build/frontends/pytorch/csrc python
Python 3.8.5 (default, Jul 27 2020, 10:09:03)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import npcomp.frontends.pytorch
2020-09-09 13:13:57.642115: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/python/npcomp/frontends/pytorch/__init__.py", line 8, in <module>
    from _torch_mlir import _get_mlir
ImportError: cannot import name '_get_mlir' from '_torch_mlir' (build/frontends/pytorch/csrc/_torch_mlir.so)
```

**Comment by ajarthurs** [comment]
Related commit concerning c10 Python bindings: 0d9188596553e1129fddc94345fc821c8edecfc8

**Comment by JehandadKhan** [comment]
Any workaround for this ?

**Comment by ajarthurs** [comment]
Closing because more Python bindings (including `_get_mlir`) have been added to the PyTorch frontend, so this issue is no longer relevant.
